const mongoose = require('mongoose');
const Character = require('./models/Character');

const MONGO_URI = 'mongodb+srv://paskm001_db_user:kL5Z033DMOCyeEFA@cluster0.0eij0ki.mongodb.net/dnd_db?appName=Cluster0';

const charactersToImport = [
    {
        name: 'Grale',
        image: '/avatars/hero02.png',
        race: { id: 'human', name: 'Human', bonuses: { strength: 1, dexterity: 1, constitution: 1, intelligence: 1, wisdom: 1, charisma: 1 } },
        charClass: { id: 'wizard', name: 'Wizard', hitDie: 6, icon: '/class-icons/wizard.svg' },
        level: 1,
        stats: { strength: 8, dexterity: 14, constitution: 13, intelligence: 15, wisdom: 12, charisma: 10 },
        bio: 'Академік, який покинув безпечну бібліотеку заради пошуку першоджерел магії.',
        nature: 'Інтелектуальний, методичний та дещо зарозумілий.',
        goal: 'Знайти таємне заклинання або артефакт, що змінить закони магії.',
        worldview: 'Нейтральний.',
        skills: ['Arcana', 'History', 'Investigation'],
        features: ['Arcane Recovery', 'Spellcasting'],
        spells: ['Fire Bolt', 'Mage Hand', 'Ray of Frost', 'Magic Missile', 'Shield', 'Sleep'],
        inventory: ['quarterstaff', 'spellbook', 'component-pouch', 'ink-pen', 'scroll-of-identify']
    },
    {
        name: 'Tilodar',
        image: '/avatars/hero03.png',
        race: { id: 'half-elf', name: 'Half Elf', bonuses: { charisma: 2, dexterity: 1, constitution: 1 } },
        charClass: { id: 'rogue', name: 'Rogue', hitDie: 8, icon: '/class-icons/rogue.svg' },
        level: 1,
        stats: { strength: 8, dexterity: 16, constitution: 14, intelligence: 13, wisdom: 11, charisma: 10 },
        bio: 'Вигнанець із гільдії злодіїв, який викрав не ту річ у не тієї людини.',
        nature: 'Хитрий, скептичний та схильний до іронії.',
        goal: 'Накопичити достатньо золота, щоб купити собі свободу від минулого.',
        worldview: 'Хаотично-нейтральний.',
        skills: ['Stealth', 'Sleight of Hand', 'Acrobatics', 'Deception', 'Perception'],
        features: ['Darkvision', 'Sneak Attack', 'Thieves\' Cant', 'Expertise (Stealth)'],
        inventory: ['dagger', 'leather-armor', 'thieves-tools', 'crowbar', 'lucky-coin']
    },
    {
        name: 'Leadrif',
        image: '/avatars/hero04.png',
        race: { id: 'hill-dwarf', name: 'Hill Dwarf', bonuses: { constitution: 2, wisdom: 1 } },
        charClass: { id: 'paladin', name: 'Paladin', hitDie: 10, icon: '/class-icons/paladin.svg' },
        level: 1,
        stats: { strength: 16, dexterity: 10, constitution: 14, intelligence: 8, wisdom: 12, charisma: 14 },
        bio: 'Лицар, що дав клятву захищати слабких після того, як сам ледь не загинув від рук розбійників.',
        nature: 'Самовідданий, чесний та непохитний.',
        goal: 'Викорінити несправедливість і стати прикладом честі для інших.',
        worldview: 'Законно-добрий.',
        skills: ['Athletics', 'Religion', 'Persuasion'],
        features: ['Darkvision', 'Dwarven Resilience', 'Divine Sense', 'Lay on Hands'],
        inventory: ['warhammer', 'shield', 'plate-armor', 'holy-symbol', 'prayer-book']
    },
    {
        name: 'Kargoth',
        image: '/avatars/hero05.png',
        race: { id: 'half-orc', name: 'Half Orc', bonuses: { strength: 2, constitution: 1 } },
        charClass: { id: 'barbarian', name: 'Barbarian', hitDie: 12, icon: '/class-icons/barbarian.svg' },
        level: 1,
        stats: { strength: 16, dexterity: 14, constitution: 16, intelligence: 8, wisdom: 10, charisma: 10 },
        bio: 'Вигнанець зі свого клану, чия лють у бою лякає навіть союзників.',
        nature: 'Дикий, імпульсивний та прямий.',
        goal: 'Перемогти легендарного звіра, щоб довести свою силу колишньому клану.',
        worldview: 'Хаотично-нейтральний.',
        skills: ['Athletics', 'Intimidation', 'Survival'],
        features: ['Darkvision', 'Relentless Endurance', 'Savage Attacks', 'Rage', 'Unarmored Defense'],
        inventory: ['greataxe', 'handaxe', 'explorers-pack', 'trophy-necklace']
    },
    {
        name: 'Victus',
        image: '/avatars/hero06.png',
        race: { id: 'tiefling', name: 'Tiefling', bonuses: { charisma: 2, intelligence: 1 } },
        charClass: { id: 'bard', name: 'Bard', hitDie: 8, icon: '/class-icons/bard.svg' },
        level: 1,
        stats: { strength: 8, dexterity: 14, constitution: 14, intelligence: 12, wisdom: 10, charisma: 16 },
        bio: 'Мандрівний музикант, який збирає забуті легенди та розбиті серця.',
        nature: 'Харизматичний, артистичний та красномовний.',
        goal: 'Написати баладу, яка житиме вічно і змінить хід історії.',
        worldview: 'Хаотично-добрий.',
        skills: ['Performance', 'Persuasion', 'Deception', 'Insight'],
        features: ['Darkvision', 'Hellish Resistance', 'Bardic Inspiration', 'Spellcasting'],
        spells: ['Vicious Mockery', 'Minor Illusion', 'Healing Word', 'Thunderwave', 'Charm Person', 'Thaumaturgy'],
        inventory: ['rapier', 'lute', 'diplomats-pack', 'disguise-kit']
    },
    {
        name: 'Broma',
        image: '/avatars/hero07.png',
        race: { id: 'hill-dwarf', name: 'Hill Dwarf', bonuses: { constitution: 2, wisdom: 1 } },
        charClass: { id: 'cleric', name: 'Cleric', hitDie: 8, icon: '/class-icons/cleric.svg' },
        level: 1,
        stats: { strength: 14, dexterity: 10, constitution: 15, intelligence: 10, wisdom: 16, charisma: 10 },
        bio: 'Військова медик, яка бачила занадто багато смертей. Вона служить богу життя і ковальства.',
        nature: 'Турботлива, стійка та мудра.',
        goal: 'Відновити зруйнований храм свого бога в горах.',
        worldview: 'Істинно-добрий.',
        skills: ['Medicine', 'History', 'Insight'],
        features: ['Darkvision', 'Stonecunning', 'Spellcasting', 'Divine Domain (Life)'],
        spells: ['Sacred Flame', 'Guidance', 'Bless', 'Cure Wounds', 'Guiding Bolt'],
        inventory: ['mace', 'scale-mail', 'holy-symbol', 'healers-kit', 'smith-tools']
    },
    {
        name: 'Elara',
        image: '/avatars/hero08.png',
        race: { id: 'wood-elf', name: 'Wood Elf', bonuses: { dexterity: 2, wisdom: 1 } },
        charClass: { id: 'druid', name: 'Druid', hitDie: 8, icon: '/class-icons/druid.svg' },
        level: 1,
        stats: { strength: 10, dexterity: 14, constitution: 14, intelligence: 10, wisdom: 16, charisma: 10 },
        bio: 'Охоронець стародавнього гаю, який був спалений війною.',
        nature: 'Спокійна, спостережлива та відсторонена.',
        goal: 'Відновити баланс природи в регіоні, постраждалому від магії.',
        worldview: 'Нейтральний.',
        skills: ['Nature', 'Survival', 'Animal Handling', 'Perception'],
        features: ['Darkvision', 'Fey Ancestry', 'Mask of the Wild', 'Druidic', 'Spellcasting'],
        spells: ['Druidcraft', 'Shillelagh', 'Entangle', 'Goodberry', 'Speak with Animals'],
        inventory: ['quarterstaff', 'leather-armor', 'totem', 'herbalism-kit']
    },
    {
        name: 'Shen',
        image: '/avatars/hero09.png',
        race: { id: 'human', name: 'Human', bonuses: { strength: 1, dexterity: 1, constitution: 1, intelligence: 1, wisdom: 1, charisma: 1 } },
        charClass: { id: 'monk', name: 'Monk', hitDie: 8, icon: '/class-icons/monk.svg' },
        level: 1,
        stats: { strength: 10, dexterity: 16, constitution: 13, intelligence: 10, wisdom: 16, charisma: 10 },
        bio: 'Аскет, який покинув монастир у пошуках просвітлення через пізнання світу.',
        nature: 'Зосереджений, дисциплінований та філософський.',
        goal: 'Знайти втрачені сувої свого майстра.',
        worldview: 'Законно-нейтральний.',
        skills: ['Acrobatics', 'Insight', 'Athletics'],
        features: ['Unarmored Defense', 'Martial Arts'],
        inventory: ['darts', 'monks-robe', 'holy-symbol', 'ancient-scroll']
    },
    {
        name: 'Milo',
        image: '/avatars/hero10.png',
        race: { id: 'halfling', name: 'Halfling', bonuses: { dexterity: 2, charisma: 1 } },
        charClass: { id: 'ranger', name: 'Ranger', hitDie: 10, icon: '/class-icons/ranger.svg' },
        level: 1,
        stats: { strength: 10, dexterity: 16, constitution: 14, intelligence: 10, wisdom: 14, charisma: 10 },
        bio: 'Провідник, який знає кожну стежку в диких землях.',
        nature: 'Обережний, practical та відданий друзям.',
        goal: 'Захистити кордони свого поселення від вторгнення гоблінів.',
        worldview: 'Хаотично-добрий.',
        skills: ['Survival', 'Stealth', 'Nature', 'Perception', 'Animal Handling'],
        features: ['Lucky', 'Brave', 'Favored Enemy (Goblins)', 'Natural Explorer'],
        inventory: ['longbow', 'shortsword', 'quiver', 'rope-silk', 'goblin-ear-necklace']
    },
    {
        name: 'Ignis',
        image: '/avatars/hero11.png',
        race: { id: 'dragonborn', name: 'Dragonborn', bonuses: { strength: 2, charisma: 1 } },
        charClass: { id: 'sorcerer', name: 'Sorcerer', hitDie: 6, icon: '/class-icons/sorcerer.svg' },
        level: 1,
        stats: { strength: 10, dexterity: 13, constitution: 14, intelligence: 10, wisdom: 10, charisma: 16 },
        bio: 'Нащадок драконів, в чиїх жилах тече нестримна магія.',
        nature: 'Емоційна, нестабільна та могутня.',
        goal: 'Навчитися повністю контролювати свою вроджену магію.',
        worldview: 'Хаотично-нейтральнний.',
        skills: ['Intimidation', 'Arcana'],
        features: ['Breath Weapon (Fire)', 'Damage Resistance (Fire)', 'Spellcasting', 'Wild Magic Surge'],
        spells: ['Fire Bolt', 'Light', 'Mage Hand', 'Chaos Bolt', 'Burning Hands'],
        inventory: ['dagger', 'arcane-focus', 'explorers-pack', 'burnt-amulet']
    },
    {
        name: 'Morgana',
        image: '/avatars/hero12.png',
        race: { id: 'drow', name: 'Drow (Dark Elf)', bonuses: { dexterity: 2, charisma: 1 } },
        charClass: { id: 'warlock', name: 'Warlock', hitDie: 8, icon: '/class-icons/warlock.svg' },
        level: 1,
        stats: { strength: 8, dexterity: 14, constitution: 14, intelligence: 12, wisdom: 10, charisma: 16 },
        bio: 'Вона уклала угоду з древньою сутністю з Безодні, щоб врятувати життя своєї сестри.',
        nature: 'Таємнича, маніпулятивна та рішуча.',
        goal: 'Знайти спосіб розірвати контракт зі своїм покровителем, зберігши при цьому силу.',
        worldview: 'Нейтральний.',
        skills: ['Deception', 'Arcana', 'History', 'idntimidation'],
        features: ['Otherworldly Patron (Fiend)', 'Pact Magic'],
        spells: ['Eldritch Blast', 'Prestidigitation', 'Hex', 'Hellish Rebuke'],
        inventory: ['dagger', 'arcane-focus', 'scholars-pack', 'pact-contract']
    },
    {
        name: 'Zanna',
        image: '/avatars/hero13.png',
        race: { id: 'rock-gnome', name: 'Rock Gnome', bonuses: { intelligence: 2, constitution: 1 } },
        charClass: { id: 'artificer', name: 'Artificer', hitDie: 8, icon: '/class-icons/artificer.svg' },
        level: 1,
        stats: { strength: 10, dexterity: 14, constitution: 14, intelligence: 14, wisdom: 12, charisma: 8 },
        bio: 'Колишня студентка академії магічної інженерії, яку вигнали за "надмірно вибухові" експерименти.',
        nature: 'Ексцентрична, геніальна та трохи розсіяна.',
        goal: 'Розкрити секрет створення розумних конструктів.',
        worldview: 'Хаотично-добрий',
        skills: ['Arcana', 'Investigation', 'Sleight of Hand'],
        features: ['Darkvision', 'Gnome Cunning', 'Artificer\'s Lore', 'Tinker', 'Magical Tinkering', 'Spellcasting'],
        spells: ['Mending', 'Fire Bolt', 'Cure Wounds', 'Grease', 'Detect Magic'],
        inventory: ['light-crossbow', 'tinkers-tools', 'magnifying-glass', 'clockwork-toy']
    },
    {
        name: 'Laeroth',
        image: '/avatars/hero14.png',
        race: { id: 'githyanki', name: 'Githyanki', bonuses: { strength: 2, intelligence: 1 } },
        charClass: { id: 'fighter', name: 'Fighter', hitDie: 10, icon: '/class-icons/fighter.svg' },
        level: 1,
        stats: { strength: 16, dexterity: 12, constitution: 14, intelligence: 14, wisdom: 10, charisma: 10 },
        bio: 'Воїтелька з Астрального плану, вихована у вічній війні проти Іллітидів.',
        nature: 'Мілітаристська, жорстока до ворогів, прагматична.',
        goal: 'Знайти та знищити колонію пожирачів розуму.',
        worldview: 'Законослухняно-злий',
        skills: ['Athletics', 'History', 'Intimidation'],
        features: ['Githyanki Psionics', 'Martial Prodigy', 'Fighting Style (Great Weapon Fighting)', 'Second Wind'],
        spells: ['Mage Hand (Psionic)'],
        inventory: ['greatsword', 'githyanki-armor', 'astral-compass']
    },
    {
        name: 'Darius',
        image: '/avatars/hero15.png',
        race: { id: 'human', name: 'Human', bonuses: { strength: 1, dexterity: 1, constitution: 1, intelligence: 1, wisdom: 1, charisma: 1 } },
        charClass: { id: 'paladin', name: 'Paladin (Oathbreaker)', hitDie: 10, icon: '/class-icons/paladin.svg' },
        level: 1,
        stats: { strength: 16, dexterity: 10, constitution: 14, intelligence: 10, wisdom: 8, charisma: 16 },
        bio: 'Колишній лицар світлого ордену, який розчарувався в кодексі честі після зради командування.',
        nature: 'Цинічний, владний та безжалісний.',
        goal: 'Знищити орден, якому він колись служив.',
        worldview: 'Законослухняно-злий',
        skills: ['Intimidation', 'Athletics', 'Persuasion'],
        features: ['Divine Sense', 'Lay on Hands', 'Fighting Style (Dueling)'],
        inventory: ['longsword', 'shield', 'broken-holy-symbol', 'skull-trinket']
    },
    {
        name: 'Fizzwick',
        image: '/avatars/hero16.png',
        race: { id: 'gnome', name: 'Rock Gnome', bonuses: { intelligence: 2, constitution: 1 } },
        charClass: { id: 'wizard', name: 'Wizard', hitDie: 6, icon: '/class-icons/wizard.svg' },
        level: 1,
        stats: { strength: 8, dexterity: 14, constitution: 14, intelligence: 17, wisdom: 10, charisma: 12 },
        bio: 'Геній ілюзій, який використовує магію не для війни, а для створення грандіозних шоу.',
        nature: 'Грайливий, хаотичний та непередбачуваний.',
        goal: 'Створити ілюзію, яку неможливо відрізнити від реальності.',
        worldview: 'Хаотично-нейтральний',
        skills: ['Arcana', 'Sleight of Hand', 'Deception'],
        features: ['Gnome Cunning', 'Arcane Recovery', 'Spellcasting'],
        spells: ['Minor Illusion', 'Prestidigitation', 'Silent Image', 'Color Spray', 'Disguise Self', 'Grease'],
        inventory: ['quarterstaff', 'deck-of-cards', 'colorful-robes', 'wand-of-smiles']
    },
    {
        name: 'Nyx',
        image: '/avatars/hero17.png',
        race: { id: 'tiefling', name: 'Tiefling', bonuses: { charisma: 2, intelligence: 1 } },
        charClass: { id: 'rogue', name: 'Rogue', hitDie: 8, icon: '/class-icons/rogue.svg' },
        level: 1,
        stats: { strength: 8, dexterity: 15, constitution: 12, intelligence: 14, wisdom: 10, charisma: 16 },
        bio: 'Вона виросла на вулицях, де її рогата зовнішність викликала страх. Стала найманим шпигуном.',
        nature: 'Стриманий, спостережливий маніпулятор.',
        goal: 'Знайти компромат на місцевого лорда.',
        worldview: 'Нейтральний',
        skills: ['Stealth', 'Insight', 'Investigation', 'Persuasion'],
        features: ['Darkvision', 'Hellish Resistance', 'Sneak Attack', 'Expertise (Deception)'],
        spells: ['Thaumaturgy'],
        inventory: ['shortsword', 'hand-crossbow', 'poisoners-kit', 'spies-pouch']
    },
    {
        name: 'Thorin',
        image: '/avatars/hero18.png',
        race: { id: 'dwarf', name: 'Mountain Dwarf', bonuses: { constitution: 2, strength: 2 } },
        charClass: { id: 'barbarian', name: 'Barbarian', hitDie: 12, icon: '/class-icons/barbarian.svg' },
        level: 1,
        stats: { strength: 17, dexterity: 12, constitution: 17, intelligence: 8, wisdom: 10, charisma: 8 },
        bio: 'Воїн, який впадає у бойовий транс, забуваючи про біль.',
        nature: 'Грубий, прямий та нестримний.',
        goal: 'Знайти смерть у славній битві проти дракона.',
        worldview: 'Хаотично-добрий',
        skills: ['Athletics', 'Survival', 'Intimidation'],
        features: ['Darkvision', 'Dwarven Resilience', 'Rage', 'Unarmored Defense'],
        inventory: ['greataxe', 'broken-anvil-piece', 'drinking-horn']
    },
    {
        name: 'Sylas',
        image: '/avatars/hero19.png',
        race: { id: 'half-elf', name: 'Half-Elf', bonuses: { charisma: 2, dexterity: 1, constitution: 1 } },
        charClass: { id: 'warlock', name: 'Warlock (Archfey)', hitDie: 8, icon: '/class-icons/warlock.svg' },
        level: 1,
        stats: { strength: 8, dexterity: 14, constitution: 14, intelligence: 10, wisdom: 12, charisma: 17 },
        bio: 'Загубившись у лісі в дитинстві, він уклав угоду з Королевою Фей, щоб знайти вихід.',
        nature: 'Мрійливий, загадковий та трохи божевільний.',
        goal: 'Виконати три забаганки своєї покровительки.',
        worldview: 'Хаотично-нейтральний',
        skills: ['Nature', 'Deception', 'Persuasion'],
        features: ['Fey Ancestry', 'Otherworldly Patron (Archfey)', 'Pact Magic'],
        spells: ['Eldritch Blast', 'Minor Illusion', 'Faerie Fire', 'Sleep'],
        inventory: ['quarterstaff', 'fey-lantern', 'satchel-of-glitter']
    },
    {
        name: 'Grom',
        image: '/avatars/hero20.png',
        race: { id: 'half-orc', name: 'Half Orc', bonuses: { strength: 2, constitution: 1 } },
        charClass: { id: 'ranger', name: 'Ranger', hitDie: 10, icon: '/class-icons/ranger.svg' },
        level: 1,
        stats: { strength: 16, dexterity: 12, constitution: 14, intelligence: 10, wisdom: 14, charisma: 8 },
        bio: 'Мисливець за головами, який спеціалізується на вилові монстрів у міських каналізаціях.',
        nature: 'Мовчазний професіонал.',
        goal: 'Вполювати вервольфа, який тероризує передмістя.',
        worldview: 'Законослухняно-нейтральний',
        skills: ['Survival', 'Perception', 'Athletics'],
        features: ['Darkvision', 'Relentless Endurance', 'Favored Enemy (Monstrosities)', 'Natural Explorer (Urban)'],
        inventory: ['battleaxe', 'hand-crossbow', 'hunters-trap', 'monster-pouch']
    },
    {
        name: 'Vanrya',
        image: '/avatars/hero21.png',
        race: { id: 'human', name: 'Human', bonuses: { strength: 1, dexterity: 1, constitution: 1, intelligence: 1, wisdom: 1, charisma: 1 } },
        charClass: { id: 'druid', name: 'Druid (Spore)', hitDie: 8, icon: '/class-icons/druid.svg' },
        level: 1,
        stats: { strength: 10, dexterity: 12, constitution: 14, intelligence: 12, wisdom: 16, charisma: 10 },
        bio: 'Вона не поклоняється квітам та деревам, вона поклоняється грибам, плісняві та розкладу.',
        nature: 'Похмура, філософська та моторошна.',
        goal: 'Поширити спори свого священного гриба на нові землі.',
        worldview: 'Нейтрально-злий',
        skills: ['Medicine', 'Nature', 'Survival'],
        features: ['Druidic', 'Spellcasting'],
        spells: ['Chill Touch', 'Poison Spray', 'Inflict Wounds', 'Detect Poison and Disease'],
        inventory: ['quarterstaff', 'wooden-shield', 'pouch-of-spores']
    },
    {
        name: 'Lyra',
        image: '/avatars/hero22.png',
        race: { id: 'drow', name: 'Drow (Dark Elf)', bonuses: { dexterity: 2, charisma: 1 } },
        charClass: { id: 'bard', name: 'Bard', hitDie: 8, icon: '/class-icons/bard.svg' },
        level: 1,
        stats: { strength: 8, dexterity: 16, constitution: 12, intelligence: 12, wisdom: 10, charisma: 16 },
        bio: 'Акробатка цирку, яка втекла, щоб побачити світ. Використовує виступи як відволікання.',
        nature: 'Оптимістична, смілива та балакуча.',
        goal: 'Стати найвідомішою артисткою королівства.',
        worldview: 'Хаотично-добрий',
        skills: ['Acrobatics', 'Performance', 'Persuasion', 'Sleight of Hand'],
        features: ['Lucky', 'Brave', 'Bardic Inspiration', 'Spellcasting'],
        spells: ['Vicious Mockery', 'Dancing Lights', 'Charm Person', 'Feather Fall', 'Heroism'],
        inventory: ['rapier', 'tambourine', 'juggling-balls', 'costume']
    },
    {
        name: 'Kael',
        image: '/avatars/hero23.png',
        race: { id: 'high-elf', name: 'High Elf', bonuses: { dexterity: 2, intelligence: 1 } },
        charClass: { id: 'cleric', name: 'Cleric (Light)', hitDie: 8, icon: '/class-icons/cleric.svg' },
        level: 1,
        stats: { strength: 10, dexterity: 12, constitution: 12, intelligence: 12, wisdom: 16, charisma: 13 },
        bio: 'Інквізитор церкви Світла. Він не лікує, він випалює єресь вогнем.',
        nature: 'Суворий, нетерпимий та палкий.',
        goal: 'Очистити світ від нежиті будь-якою ціною.',
        worldview: 'Законослухняно-нейтральний',
        skills: ['Religion', 'History', 'Insight'],
        features: ['Darkvision', 'Fey Ancestry', 'Spellcasting', 'Warding Flare'],
        spells: ['Light', 'Sacred Flame', 'Burning Hands', 'Faerie Fire', 'Guiding Bolt'],
        inventory: ['mace', 'scale-mail', 'holy-symbol', 'censer-of-purification']
    },
    {
        name: 'Toar',
        image: '/avatars/hero24.png',
        race: { id: 'dragonborn', name: 'Silver Dragonborn', bonuses: { strength: 2, charisma: 1 } },
        charClass: { id: 'fighter', name: 'Fighter', hitDie: 10, icon: '/class-icons/fighter.svg' },
        level: 1,
        stats: { strength: 17, dexterity: 10, constitution: 14, intelligence: 10, wisdom: 12, charisma: 12 },
        bio: 'Шляхетний воїн з далеких північних земель. Використовує крижане дихання та алебарду.',
        nature: 'Холодний, розважливий та чесний.',
        goal: 'Повернути фамільну зброю, викрадену бандитами.',
        worldview: 'Законослухняно-добрий',
        skills: ['Athletics', 'History', 'Intimidation'],
        features: ['Breath Weapon (Cold)', 'Damage Resistance (Cold)', 'Fighting Style (Defense)', 'Second Wind'],
        inventory: ['halberd', 'heavy-armor', 'silver-dragon-scale']
    },
    {
        name: 'Ember',
        image: '/avatars/hero25.png',
        race: { id: 'genasi', name: 'Fire Genasi', bonuses: { constitution: 2, intelligence: 1 } },
        charClass: { id: 'sorcerer', name: 'Sorcerer (Draconic)', hitDie: 6, icon: '/class-icons/sorcerer.svg' },
        level: 1,
        stats: { strength: 10, dexterity: 14, constitution: 14, intelligence: 10, wisdom: 8, charisma: 16 },
        bio: 'Її волосся палає, коли вона злиться. Магія вогню тече в її жилах.',
        nature: 'Запальна, пристрасна та небезпечна.',
        goal: 'Знайти спосіб приборкати свій внутрішній вогонь.',
        worldview: 'Хаотично-нейтральний',
        skills: ['Arcana', 'Intimidation'],
        features: ['Darkvision', 'Fire Resistance', 'Draconic Resilience', 'Spellcasting'],
        spells: ['Fire Bolt', 'Control Flames', 'Burning Hands', 'Shield', 'Produce Flame'],
        inventory: ['dagger', 'fire-opal-focus', 'burnt-journal']
    },
    {
        name: 'Swift',
        image: '/avatars/hero26.png',
        race: { id: 'wood-elf', name: 'Wood Elf', bonuses: { dexterity: 2, wisdom: 1 } },
        charClass: { id: 'monk', name: 'Monk', hitDie: 8, icon: '/class-icons/monk.svg' },
        level: 1,
        stats: { strength: 10, dexterity: 17, constitution: 13, intelligence: 10, wisdom: 15, charisma: 8 },
        bio: 'Тіньовий вбивця, яка використовує стиль "П\'яного майстра" (хоча сама не п\'є).',
        nature: 'Спокійна, іронічна та смертоносна.',
        goal: 'Виконати контракт на усунення корумпованого чиновника.',
        worldview: 'Законно-зла',
        skills: ['Stealth', 'Acrobatics', 'Insight'],
        features: ['Darkvision', 'Fey Ancestry', 'Unarmored Defense', 'Martial Arts'],
        inventory: ['shortsword', 'monks-robe', 'vial-of-shadow-ink']
    },
    {
        name: 'Aldous',
        image: '/avatars/hero27.png',
        race: { id: 'human', name: 'Human', bonuses: { strength: 1, dexterity: 1, constitution: 1, intelligence: 1, wisdom: 1, charisma: 1 } },
        charClass: { id: 'artificer', name: 'Artificer (Alchemist)', hitDie: 8, icon: '/class-icons/artificer.svg' },
        level: 1,
        stats: { strength: 10, dexterity: 12, constitution: 14, intelligence: 16, wisdom: 12, charisma: 10 },
        bio: 'Колишній військовий лікар, який був позбавлений ліцензії за використання хімічних сполук.',
        nature: 'Цинічний, прагматичний та допитливий.',
        goal: 'Створити еліксир безсмертя (або хоча б панацею від чуми).',
        worldview: 'Законослухняно-нейтральний',
        skills: ['Medicine', 'Nature', 'Investigation'],
        features: ['Alchemist\'s Supplies Proficiency', 'Magical Tinkering', 'Experimental Elixir', 'Spellcasting'],
        spells: ['Acid Splash', 'Poison Spray', 'Ray of Sickness', 'Cure Wounds', 'Purify Food and Drink'],
        inventory: ['alchemists-supplies', 'acid-flask', 'vial-of-unknown-liquid']
    },
    {
        name: 'Vaelar',
        image: '/avatars/hero28.png',
        race: { id: 'drow', name: 'Drow (Dark Elf)', bonuses: { dexterity: 2, charisma: 1 } },
        charClass: { id: 'sorcerer', name: 'Sorcerer (Shadow Magic)', hitDie: 6, icon: '/class-icons/sorcerer.svg' },
        level: 1,
        stats: { strength: 8, dexterity: 16, constitution: 14, intelligence: 10, wisdom: 10, charisma: 16 },
        bio: 'Він народився під час затемнення. Його магія — це сама темрява, що оживає.',
        nature: 'Меланхолійний, тихий та лякаюче спокійний.',
        goal: 'Зрозуміти природу своєї темної сили та не дати їй поглинути себе.',
        worldview: 'Хаотично-добрий',
        skills: ['Stealth', 'Deception', 'Persuasion', 'Perception'],
        features: ['Superior Darkvision', 'Sunlight Sensitivity', 'Drow Magic', 'Eyes of the Dark', 'Strength of the Grave'],
        spells: ['Chill Touch', 'Minor Illusion', 'Dancing Lights', 'False Life', 'Sleep'],
        inventory: ['dagger', 'shadow-shard', 'drow-cloak']
    },
    {
        name: 'Q\'al',
        image: '/avatars/hero29.png',
        race: { id: 'aarakocra', name: 'Aarakocra', bonuses: { wisdom: 2 } },
        charClass: { id: 'cleric', name: 'Cleric', hitDie: 8, icon: '/class-icons/cleric.svg' },
        level: 1,
        stats: { strength: 14, dexterity: 16, constitution: 12, intelligence: 10, wisdom: 16, charisma: 8 },
        bio: 'Він спустився з найвищих піків, де шторми ніколи не вщухають. Вірить, що блискавка — правосуддя.',
        nature: 'Відсторонений, рішучий та непередбачуваний, як гроза.',
        goal: 'Полювати на елементалів землі, які оскверняють небо.',
        worldview: 'Хаотично-нейтральний',
        skills: ['Perception', 'Acrobatics', 'Nature'],
        features: ['Flight', 'Talons', 'Spellcasting', 'Wrath of the storm'],
        spells: ['Thaumaturgy', 'Guidance', 'Thunderwave', 'Fog cloud', 'Guiding bolt', 'Healing word'],
        inventory: ['spear', 'holy-symbol-storm', 'storm-glass', 'feather-pouch', 'lightning-stone']
    },
];

mongoose.connect(MONGO_URI)
    .then(async () => {
        console.log('📡 Зв\'язок з хмарою встановлено. Починаємо завантаження героїв...');
        
        await Character.insertMany(charactersToImport);
        
        console.log('✅ Всі 28 персонажів успішно імпортовані в MongoDB Atlas!');
        process.exit(0);
    })
    .catch(error => {
        console.error('❌ Помилка імпорту:', error);
        process.exit(1);
    });